### Introduction to Pandas

Pandas is a package built on top of NumPy, and provides an efficient implementation of a `DataFrame`.

DataFrames are essentially multidimensional arrays with attached row and column labels, and often with heterogeneous types and/or missing data.

NumPy’s ndarray data structure provides essential features for the type of clean, well-organized data typically seen in numerical computing tasks.

While it serves this purpose very well, its limitations become clear when we need more flexibility (e.g., attaching labels to data, working with missing data, etc.) and when attempting operations that do not map well to element-wise broadcasting (e.g., groupings, pivots, etc.), each of which is an important piece of analyzing the less structured data available in many forms in the world around us.

Pandas, and in particular its `Series` and `DataFrame` objects, builds on the NumPy array structure and provides efficient access to these sorts of “data munging” tasks that occupy much of a data scientist’s time.

### Installing and Using Pandas

[Pandas Documentation](https://pandas.pydata.org/)

Once Pandas is installed, you can import it and check the version:

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'3.0.1'

### Pandas Objects

Pandas objects can be thought of as enhanced versions of NumPy structured arrays in which the rows and columns
are identified with labels rather than simple integer indices. 

The three fundamental Pandas data structures include:
- Series
- DataFrame
- Index

####  The Pandas Series Object

A Pandas Series is a one-dimensional array of indexed data.
 
It can be created from a list or array as follows:

In [2]:
data = pd.Series([0.1, 0.2, 0.3, 0.4, 0.5])
data

0    0.1
1    0.2
2    0.3
3    0.4
4    0.5
dtype: float64

the Series wraps both a sequence of values and a sequence of indices, which we can access with the `values` and 
`index` attributes.

In [4]:
data.values

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [5]:
data.index

RangeIndex(start=0, stop=5, step=1)

In [6]:
data

0    0.1
1    0.2
2    0.3
3    0.4
4    0.5
dtype: float64

In [14]:
data[1:3]

1    0.2
2    0.3
dtype: float64

The index is an array-like object of type `pd.Index`, which we’ll discuss later in more detail

Like with a NumPy array, data can be accessed by the associated index

In [8]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [10]:
data[2]

np.float64(0.75)

In [103]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [102]:
data[1:3]

1    0.50
2    0.75
dtype: float64

#### Series as generalized NumPy array

From what we’ve seen so far, it may look like the Series object is basically interchangeable with a one-dimensional NumPy array. 

The essential difference is the presence of the index: while the Numpy Array has an implicitly defined integer index used to access the values, the Pandas Series has an explicitly defined index associated with the values.

This explicit index definition gives the Series object additional capabilities. 

For example, the index need not be an integer, but can consist of values of any desired type. For example, if we wish, we can use strings as an index:

In [16]:
data = pd.Series([0.1, 0.2, 0.3, 0.4, 0.5], index=['a', 'b', 'c', 'd', 'e'])
data

a    0.1
b    0.2
c    0.3
d    0.4
e    0.5
dtype: float64

In [18]:
data['a':'d']

a    0.1
b    0.2
c    0.3
d    0.4
dtype: float64

In [19]:
data['c']

np.float64(0.3)

####  Series as specialized dictionary

you can think of a Pandas Series a bit like a specialization of a Python dictionary.

A `dictionary` is a structure that maps arbitrary keys to a set of arbitrary values, and a `Series` is a structure which maps typed keys to a set of typed values. 

The type information of a Pandas Series makes it much more efficient than Python dictionaries for certain operations.

The Series-as-dictionary analogy can be made even more clear by constructing a Series object directly from a Python dictionary:

In [20]:
student_dict = {
    'name':'Alice', 
    'age':25,
    'city':'New York'
}
student_series = pd.Series(student_dict)
student_series

name       Alice
age           25
city    New York
dtype: object

In [21]:
population_dict = {'California': 38332521,
                    'Texas': 26448193,
                    'New York': 19651127,
                    'Florida': 19552860,
                    'Illinois': 12882135}

population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [23]:
population['Texas':'Florida']

Texas       26448193
New York    19651127
Florida     19552860
dtype: int64

By default, a Series will be created where the index is drawn from the sorted keys. 

From here, typical dictionary-style item access can be performed:

In [28]:
population['Texas']

np.int64(26448193)

Unlike a dictionary, though, the Series also supports array-style operations such as slicing:

In [16]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [17]:
population['Texas':'Florida']

Texas       26448193
New York    19651127
Florida     19552860
dtype: int64

#### Constructing Series objects

We’ve already seen a few ways of constructing a Pandas Series from scratch; all of them are some version of the following:

`pd.Series(data, index=index)`

where index is an optional argument, and data can be one of many entities.

For example, data can be a list or NumPy array, in which case index defaults to an integer sequence:

In [24]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [25]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [26]:
pd.Series({2: 'a', 4: 'b', 6: 'c'})

2    a
4    b
6    c
dtype: str

`data` can be a scalar, which is repeated to fill the specified index:

In [115]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

`data` can be a dictionary, in which index defaults to the sorted dictionary keys:

In [116]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

###  The Pandas DataFrame Object

Like the `Series` object discussed in the previous section, the `DataFrame` can be thought of either as a `generalization of a NumPy array`, or as a `specialization of a Python dictionary`. 

We’ll now take a look at each of these perspectives.

#### DataFrame as a generalized NumPy array

If a `Series` is an analog of a one-dimensional array with flexible indices, a `DataFrame` is an analog of a two-dimensional array with both flexible row indices and flexible column names.

You can think of a DataFrame as a sequence of aligned Series objects. Here, by `aligned` we mean that they share
the same index.

let’s first construct a new Series listing the area of each of the five states discussed in the previous section:

In [27]:
area_dict = {'California': 423967, 
             'Texas': 695662, 
             'New York': 141297,
             'Florida': 170312, 
             'Illinois': 149995}

area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [29]:
states = pd.DataFrame({'population': population, 'area': area})

In [30]:
states

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [31]:
states.population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: population, dtype: int64

Now that we have this along with the population Series from before, we can use a dictionary to construct a single two-dimensional object containing this information:

In [20]:
states = pd.DataFrame({'population': population, 'area': area})
states

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

Like the Series object, the DataFrame has an index attribute that gives access to the index labels:

In [21]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

Additionally, the DataFrame has a columns attribute, which is an Index object holding the column labels:

In [22]:
states.columns

Index(['population', 'area'], dtype='object')

Thus the DataFrame can be thought of as a generalization of a two dimensional NumPy array, where both the rows and columns have a generalized index for accessing the data.

####  DataFrame as specialized dictionary

Similarly, we can also think of a DataFrame as a specialization of a dictionary. 

Where a dictionary maps a key to a value, a DataFrame maps a column name to a Series of column data.

For example, asking for the `area` attribute returns the Series object containing the areas

In [32]:
states

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [33]:
states.population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: population, dtype: int64

####  Constructing DataFrame objects

A Pandas DataFrame can be constructed in a variety of ways. 

##### From a single Series object

A `DataFrame` is a collection of Series objects, and a single column DataFrame can be constructed from a single Series:

In [34]:
pd.DataFrame(population, columns=['population'])

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

#### From a list of dicts

Any list of dictionaries can be made into a DataFrame.

In [35]:
np.arange(3)

array([0, 1, 2])

In [37]:
# create a list of dictionaries
data = [{'a': 1, 'b': 2 * i}
        for i in range(3)]
data
pd.DataFrame(data)

   a  b
0  1  0
1  1  2
2  1  4

####  From a dictionary of Series objects

A DataFrame can be constructed from a dictionary of Series objects as well

In [38]:
pd.DataFrame({'population': population, 'area':area})

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

####  From a two-dimensional NumPy array

Given a two-dimensional array of data, we can create a DataFrame with any specified column and index names.

In [41]:
array_1 = np.random.rand(3, 2)
array_1

array([[0.06245276, 0.50239524],
       [0.10966734, 0.78674421],
       [0.10648947, 0.24256789]])

In [43]:
pd.DataFrame(array_1, columns=['Column 1', 'Column 2'], index=['a', 'b', 'c'])

   Column 1  Column 2
a  0.062453  0.502395
b  0.109667  0.786744
c  0.106489  0.242568

In [29]:
pd.DataFrame(np.random.rand(3,2), 
             columns=['Column_1', 'Column_2'],
             index= ['a', 'b', 'c'])

   Column_1  Column_2
a  0.797419  0.212422
b  0.050850  0.080968
c  0.319803  0.431642

### The Pandas Index Object

We have seen here that both the `Series` and `DataFrame` objects contain an `explicit index` that lets you reference and modify data.

This Index object can be thought of either as an `immutable array` or as an `ordered set` (technically a multi-set, as Index objects may contain repeated values).

In [44]:
# an Index from a list of integers

ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

In [46]:
ind[2]

np.int64(5)

#### Index as immutable array

The Index in many ways operates like an array.

In [47]:
ind

Index([2, 3, 5, 7, 11], dtype='int64')

In [48]:
ind[2]

np.int64(5)

In [50]:
ind[::2]

Index([2, 5, 11], dtype='int64')

One difference between Index objects and NumPy arrays is that indices are `immutable`–that is, they cannot be modified via the normal means:

In [51]:
ind

Index([2, 3, 5, 7, 11], dtype='int64')

In [52]:
ind[1] = 0

TypeError: Index does not support mutable operations

This immutability makes it safer to share indices between multiple DataFrames and arrays, without the potential for side effects from inadvertent index modification.

#### Index as ordered set

Pandas objects are designed to facilitate operations such as `joins` across datasets, which depend on many aspects of set arithmetic.

The Index object follows many of the conventions used by Python’s built-in set data structure, so that unions,intersections, differences, and other combinations can be computed

In [53]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [54]:
indA & indB  # intersection

Index([0, 3, 5, 7, 9], dtype='int64')

In [6]:
# Correct and reliable way:
intersection = indA.intersection(indB)
print(intersection)

Index([3, 5, 7], dtype='int64')

In [7]:
indA | indB  # union

Index([3, 3, 5, 7, 11], dtype='int64')

In [ ]:
#The .union() method merges both index sets and automatically removes duplicates.
union = indA.union(indB)
print(union)

Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

### Data Indexing and Selection

In the previous lessons, we looked in detail at methods and tools to access, set, and modify values in NumPy arrays. 

These included indexing `(e.g., arr[2, 1])`, slicing `(e.g., arr[:, 1:5])`, masking `(e.g., arr[arr > 0])`, fancy indexing `(e.g., arr[0, [1, 5]])`, and combinations thereof `(e.g., arr[:, [1, 5]])`.

Here we’ll look at similar means of accessing and modifying values in Pandas `Series` and `DataFrame` objects.

We’ll start with the simple case of the `one-dimensional Series` object, and then move on to the more complicated `two-dimesnional DataFrame` object.

### Data Selection in Series

A Series object acts in many ways like a one-dimensional NumPy array, and in many ways like a standard Python dictionary.

#### Series as dictionary

Like a dictionary, the Series object provides a mapping from a collection of keys to a collection of values:

In [55]:
data = pd.Series([1, 2, 3, 4, 5, 6, 7], index=['a', 'b', 'c', 'd', 'e', 'f', 'g'])
data

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int64

In [56]:
data['c']

np.int64(3)

We can also use dictionary-like Python expressions and methods to examine the keys/indices and values:

In [10]:
data

a    1
b    2
c    3
d    4
dtype: int64

In [11]:
'a' in data

True

In [57]:
data.keys()

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='str')

In [58]:
list(data.items())

[('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5), ('f', 6), ('g', 7)]

Series objects can even be modified with a dictionary-like syntax.

Just as you can extend a dictionary by assigning to a new key, you can extend a Series by assigning to a new index value:

In [59]:
data

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int64

In [60]:
data['e'] = 10
data

a     1
b     2
c     3
d     4
e    10
f     6
g     7
dtype: int64

#### Series as one-dimensional array

A Series builds on this dictionary-like interface and provides `array-style` item selection via the same basic mechanisms as NumPy arrays – that is, `slices`, `masking`, and `fancy indexing`.

In [61]:
data

a     1
b     2
c     3
d     4
e    10
f     6
g     7
dtype: int64

In [62]:
# slicing by explicit index
data['b':'e']

b     2
c     3
d     4
e    10
dtype: int64

In [63]:
data

a     1
b     2
c     3
d     4
e    10
f     6
g     7
dtype: int64

In [25]:
# slicing by implicit integer index
data[1:5]

b    2
c    3
d    4
e    5
dtype: int64

Notice that when slicing with an explicit index `(i.e., data['a':'c'])`, the final index is included in the slice, while when slicing with an implicit index `(i.e., data[0:2])`, the final index is excluded from the slice.

In [65]:
data

a     1
b     2
c     3
d     4
e    10
f     6
g     7
dtype: int64

In [66]:
data[data <= 5]

a    1
b    2
c    3
d    4
dtype: int64

In [67]:
data[data <= 2]

a    1
b    2
dtype: int64

In [68]:
data

a     1
b     2
c     3
d     4
e    10
f     6
g     7
dtype: int64

In [69]:
data[(data >= 2) & (data <= 5)]

b    2
c    3
d    4
dtype: int64

In [29]:
# masking
data[(data > 2) & (data < 5)]

a    4
c    3
d    4
dtype: int64

In [70]:
data

a     1
b     2
c     3
d     4
e    10
f     6
g     7
dtype: int64

In [71]:
# fancy indexing
data[['a', 'c', 'e']]

a     1
c     3
e    10
dtype: int64

#### Indexers: loc and iloc

These slicing and indexing conventions can be a source of confusion. 

For example, If your `Series` has an explicit integer index, an `indexing` operation such as `data[1]` will use the explicit indices, while a `slicing` operation like `data[1:3]` will use the implicit Python-style index.

In [3]:
data = pd.Series(['a', 'b', 'c', 'd', 'e', 'f'], index=[1, 2, 3, 4, 5, 6])
data

1    a
2    b
3    c
4    d
5    e
6    f
dtype: str

In [ ]:
# using the explicit index
data[3]

'c'

In [6]:
#slicing by explicit index
data[2:5]

3    c
4    d
5    e
dtype: str

In [38]:
# implicit index when slicing
data[1:3]

2    b
3    c
dtype: object

Because of this potential confusion in the case of integer indexes, Pandas provides some special `indexer` attributes that explicitly expose certain indexing schemes.

These are not functional methods, but attributes that expose a particular slicing interface to the data in the `Series`.

First, the `loc` attribute allows indexing and slicing that always references the explicit index:

In [7]:
data

1    a
2    b
3    c
4    d
5    e
6    f
dtype: str

In [12]:
# explicit index when slicing
data.loc[2:5]

2    b
3    c
4    d
5    e
dtype: str

In [13]:
data

1    a
2    b
3    c
4    d
5    e
6    f
dtype: str

In [21]:
data.loc[2:5]

2    b
3    c
4    d
5    e
dtype: str

In [46]:
# explicit index when indexing
data.loc[1]

'a'

In [47]:
data

1    a
2    b
3    c
4    d
5    e
6    f
dtype: object

In [38]:
# explicit index when slicing
data.loc[1:3]

1    a
2    b
3    c
dtype: object

The `iloc` attribute allows indexing and slicing that always references the implicit Python-style index:

In [50]:
data

1    a
2    b
3    c
4    d
5    e
6    f
dtype: object

In [51]:
data.iloc[1]

'b'

In [41]:
data.iloc[1:3]

2    b
3    c
dtype: object

One guiding principle of Python code is that `explicit` is better than `implicit.`

The explicit nature of `loc` and `iloc` make them very useful in maintaining clean and readable code; especially in the case of integer indexes.

### Data Selection in DataFrame

A `DataFrame` acts in many ways like a two-dimensional or structured array, and in other ways like a dictionary of `Series` structures sharing the same index.

#### DataFrame as a dictionary

In [23]:
# example on areas and populations of states:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})

population = pd.Series({'California': 39538223, 'Texas': 29145505,
                  'New York': 20201249, 'Florida': 21538187,
                  'Illinois': 12812508})

data = pd.DataFrame({'area': area, 'population': population})
data

              area  population
California  423967    39538223
Texas       695662    29145505
New York    141297    20201249
Florida     170312    21538187
Illinois    149995    12812508

The individual Series that make up the columns of the DataFrame can be accessed via dictionary-style indexing of the column name:

In [24]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

Equivalently, we can use attribute-style access with column names that are strings:

In [25]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [26]:
data.population

California    39538223
Texas         29145505
New York      20201249
Florida       21538187
Illinois      12812508
Name: population, dtype: int64

This dictionary-style syntax can also be used to modify the object, in this case adding a new column:

In [27]:
data['density'] = data['population'] / data['area']
data

              area  population     density
California  423967    39538223   93.257784
Texas       695662    29145505   41.896072
New York    141297    20201249  142.970120
Florida     170312    21538187  126.463121
Illinois    149995    12812508   85.419567

This is an example of `element-by-element` arithmetic between Series objects

#### DataFrame as two-dimensional array

We can also view the DataFrame as an enhanced two-dimensional array.

We can examine the raw underlying data array using the `values` attribute:

In [28]:
data

              area  population     density
California  423967    39538223   93.257784
Texas       695662    29145505   41.896072
New York    141297    20201249  142.970120
Florida     170312    21538187  126.463121
Illinois    149995    12812508   85.419567

In [29]:
data.values

array([[4.23967000e+05, 3.95382230e+07, 9.32577842e+01],
       [6.95662000e+05, 2.91455050e+07, 4.18960717e+01],
       [1.41297000e+05, 2.02012490e+07, 1.42970120e+02],
       [1.70312000e+05, 2.15381870e+07, 1.26463121e+02],
       [1.49995000e+05, 1.28125080e+07, 8.54195673e+01]])

With this picture in mind, many familiar array-like observations can be done on the `DataFrame` itself.

For example, we can `transpose` the full DataFrame to swap rows and columns:

In [30]:
data

              area  population     density
California  423967    39538223   93.257784
Texas       695662    29145505   41.896072
New York    141297    20201249  142.970120
Florida     170312    21538187  126.463121
Illinois    149995    12812508   85.419567

In [31]:
data.T

,California,Texas,New York,Florida,Illinois
area,4.239670e+05,6.956620e+05,1.412970e+05,1.703120e+05,1.499950e+05
population,3.953822e+07,2.914550e+07,2.020125e+07,2.153819e+07,1.281251e+07
density,9.325778e+01,4.189607e+01,1.429701e+02,1.264631e+02,8.541957e+01

When it comes to indexing of DataFrame objects, however, it is clear that the dictionary-style indexing of columns precludes our ability to simply treat it as a NumPy array.

In particular, passing a single index to an array accesses a row:

In [32]:
data.values

array([[4.23967000e+05, 3.95382230e+07, 9.32577842e+01],
       [6.95662000e+05, 2.91455050e+07, 4.18960717e+01],
       [1.41297000e+05, 2.02012490e+07, 1.42970120e+02],
       [1.70312000e+05, 2.15381870e+07, 1.26463121e+02],
       [1.49995000e+05, 1.28125080e+07, 8.54195673e+01]])

In [33]:
data.values[0]

array([4.23967000e+05, 3.95382230e+07, 9.32577842e+01])

and passing a single “index” to a DataFrame accesses a column:

In [34]:
data

              area  population     density
California  423967    39538223   93.257784
Texas       695662    29145505   41.896072
New York    141297    20201249  142.970120
Florida     170312    21538187  126.463121
Illinois    149995    12812508   85.419567

In [35]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

Thus for array-style indexing, we need another convention.

Here Pandas again uses the `loc` and`iloc`indexers mentioned earlier.

Using the `iloc` indexer, we can index the underlying array as if it is a simple NumPy array (using the implicit Python-style index), but the DataFrame index and column labels are maintained in the result:

In [36]:
data

              area  population     density
California  423967    39538223   93.257784
Texas       695662    29145505   41.896072
New York    141297    20201249  142.970120
Florida     170312    21538187  126.463121
Illinois    149995    12812508   85.419567

In [46]:
data.loc['California':'New York']

              area  population     density
California  423967    39538223   93.257784
Texas       695662    29145505   41.896072
New York    141297    20201249  142.970120

In [47]:
data.iloc[0:3]

              area  population     density
California  423967    39538223   93.257784
Texas       695662    29145505   41.896072
New York    141297    20201249  142.970120

In [44]:
data.iloc[:3, :2]

              area  population
California  423967    39538223
Texas       695662    29145505
New York    141297    20201249

In [42]:
data[0:4]

              area  population     density
California  423967    39538223   93.257784
Texas       695662    29145505   41.896072
New York    141297    20201249  142.970120
Florida     170312    21538187  126.463121

In [65]:
data.iloc[0:4]

              area  population     density
California  423967    39538223   93.257784
Texas       695662    29145505   41.896072
New York    141297    20201249  142.970120
Florida     170312    21538187  126.463121

In [66]:
data

              area  population     density
California  423967    39538223   93.257784
Texas       695662    29145505   41.896072
New York    141297    20201249  142.970120
Florida     170312    21538187  126.463121
Illinois    149995    12812508   85.419567

In [48]:
data

              area  population     density
California  423967    39538223   93.257784
Texas       695662    29145505   41.896072
New York    141297    20201249  142.970120
Florida     170312    21538187  126.463121
Illinois    149995    12812508   85.419567

In [49]:
data.iloc[2:, ::2]  # first two rows and first two columns

            area     density
New York  141297  142.970120
Florida   170312  126.463121
Illinois  149995   85.419567

Similarly, using the `loc` indexer we can index the underlying data in an array-like style but using the explicit index and column names:

In [69]:
data

              area  population     density
California  423967    39538223   93.257784
Texas       695662    29145505   41.896072
New York    141297    20201249  142.970120
Florida     170312    21538187  126.463121
Illinois    149995    12812508   85.419567

In [46]:
data.loc['New York':, 'population':]

          population     density
New York    20201249  142.970120
Florida     21538187  126.463121
Illinois    12812508   85.419567

In [50]:
data.loc[:'Florida', :'population']

              area  population
California  423967    39538223
Texas       695662    29145505
New York    141297    20201249
Florida     170312    21538187

Any of these indexing conventions may also be used to set or modify values; this is done in the standard way that you might be accustomed to from working with NumPy:

In [47]:
data

              area  population     density
California  423967    39538223   93.257784
Texas       695662    29145505   41.896072
New York    141297    20201249  142.970120
Florida     170312    21538187  126.463121
Illinois    149995    12812508   85.419567

In [69]:
data.iloc[0, 2] = 90
data

              area  population     density
California  423967    39538223   90.000000
Texas       695662    29145505   41.896072
New York    141297    20201249  142.970120
Florida     170312    21538187  126.463121
Illinois    149995    12812508   85.419567

### Additional indexing conventions

`indexing` refers to columns, `slicing` refers to rows:

In [89]:
data

              area  population     density
California  423967    39538223   90.000000
Texas       695662    29145505   41.896072
New York    141297    20201249  142.970120
Florida     170312    21538187  126.463121
Illinois    149995    12812508   85.419567

In [91]:
data['Florida':'Illinois']

            area  population     density
Florida   170312    21538187  126.463121
Illinois  149995    12812508   85.419567

Such slices can also refer to rows by number rather than by index:

In [92]:
data

              area  population     density
California  423967    39538223   90.000000
Texas       695662    29145505   41.896072
New York    141297    20201249  142.970120
Florida     170312    21538187  126.463121
Illinois    149995    12812508   85.419567

In [93]:
data[1:3]

            area  population     density
Texas     695662    29145505   41.896072
New York  141297    20201249  142.970120

Similarly, direct masking operations are also interpreted row-wise rather than column-wise:

In [94]:
data

              area  population     density
California  423967    39538223   90.000000
Texas       695662    29145505   41.896072
New York    141297    20201249  142.970120
Florida     170312    21538187  126.463121
Illinois    149995    12812508   85.419567

In [70]:
#masking
data[data.density > 100]

            area  population     density
New York  141297    20201249  142.970120
Florida   170312    21538187  126.463121